version: "2"
services:
  web:
    build:
      context: .
      dockerfile: "./Dockerfile.ci"
    ports:
      - "8000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@avon-ci_db_1:5432/avon
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=avon
    ports:
      - "5432:5432"
