version: "2"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:3000"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=avon
    ports:
      - "5432:5432"
