version: "2"

services:
  web:
    build:
      context: .
      dockerfile: "./Dockerfile.ci"
    ports:
      - "8000:3000"
    depends_on:
      - db
    environment:
      - JWT_SECRET
      - JWT_REFRESH_SECRET
      - DATABASE_URL
      - TEST_REFRESH_TOKEN
      - TEST_ACCESS_TOKEN
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=avon
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "5432:5432"
