version: "2"
services:
  web:
    build:
      context: .
      dockerfile: "./Dockerfile.ci"
    ports:
      - "8000:3000"
    depends_on:
      - db
    environment:
      - JWT_SECRET
      - JWT_REFRESH_SECRET
      - DATABASE_URL
    volumes:
      - ./node_modules:/app/node_modules
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=avon
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "5432:5432"
