version: "2"
services:
  web:
    build:
      context: .
      dockerfile: "./Dockerfile.ci"
    ports:
      - "8000:3000"
    depends_on:
      - db
    volumes:
      - ".:/app:rw"
  db:
    image: postgres:latest
    env_file: .env
    ports:
      - "5432:5432"
